### ISSUE TITLE
Pattern of story point labels become configurable

### ISSUE THREAD

**Issue by azmin8744** [ryz310/github_project_enhancer#9]
Definitely awesome feature, story points calculating is introduced, but unfortunately my project has labels: "1point", "2points", "3points" ..., so that feature is not compatible for my project.
This extension would be more useful if the pattern of labels become configurable.

And I made some modifications to solve these issues. Please see diff: https://github.com/ryz310/github_project_enhancer/compare/master...azmin8744:configurable-label-pattern

**Comment by ryz310** [comment]
Hi, @azmin8744 san.
I've seen your diff. It looks awesome! Would you like create a PR?
